---
- name: Create opt folder
  file: path={{base_dir}}/opt state=directory

- name: Create tmp folder
  file: path={{base_dir}}/tmp state=directory

- name: Copy sources
  copy: src=sources/{{item}} dest={{base_dir}}/tmp/{{item}}
  with_items:
    - ansible-2.0.1.0.tar.gz
    - ecdsa-0.13-py2.py3-none-any.whl
    - httplib2-0.9.2.tar.gz
    - Jinja2-2.8-py2.py3-none-any.whl
    - libffi-3.2.1.tar.gz
    - MarkupSafe-0.23.tar.gz
    - openssl-1.0.2g.tar.gz
    - paramiko-1.16.0-py2.py3-none-any.whl
    - paramiko-1.16.0.tar.gz
    - pycrypto-2.6.1.tar.gz
    - Python-2.7.11.tgz
    - PyYAML-3.11.tar.gz
    - setuptools-20.7.0-py2.py3-none-any.whl
    - six-1.10.0-py2.py3-none-any.whl
    - zlib-1.2.8.tar.gz